# Welcome to Abrar's Porfolio!

# URL settings
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
telegram_comment_id: vqJkgnAX

markdown: kramdown
markdown_ext: "markdown, mkdown, mkdn, mkd, md"
highlighter: rouge

# Theme settings
theme:
permalink: /:title/

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  posts:
    output: true
    permalink: /blogs/:slug/
  projects:
    output: true
    permalink: /projects/:slug/
    sort_by: "date"
  arts:
    output: true
    permalink: /arts/:slug/
    sort_by: "date"

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "arts"
    values:
      layout: "art"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - run
  - prodrun
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
